/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponseDto: {
            /**
             * @description Error message
             * @example Validation failed
             */
            message: string;
            /**
             * @description Error code
             * @example VALIDATION_ERROR
             */
            code: string;
            /**
             * @description HTTP status code
             * @example 400
             */
            statusCode: number;
            /** @description Validation errors */
            errors?: string[];
            /**
             * @description Error timestamp
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
            /**
             * @description Request path that caused the error
             * @example /api/users
             */
            path?: string;
        };
        ValidationErrorDto: {
            /**
             * @description Field name that failed validation
             * @example email
             */
            field: string;
            /**
             * @description Validation constraints that were violated
             * @example {
             *       "isEmail": "Must be a valid email address"
             *     }
             */
            constraints: Record<string, never>;
            /**
             * @description The value that failed validation
             * @example invalid-email
             */
            value?: string;
        };
        SuccessResponseDto: {
            /**
             * @description Success status
             * @example true
             */
            success: boolean;
            /**
             * @description Success message
             * @example Operation completed successfully
             */
            message: string;
            /** @description Response data */
            data?: unknown;
            /**
             * @description Response timestamp
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
        };
        PaginationQueryDto: {
            /**
             * @description Page number
             * @example 1
             */
            page?: number;
            /**
             * @description Items per page
             * @example 10
             */
            limit?: number;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseDto"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseDto"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseDto"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseDto"];
            };
        };
    };
    parameters: {
        /** @description Page number for pagination */
        PageParameter: number;
        /** @description Number of items per page */
        LimitParameter: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
